Attempt to make sure that all streams are closed properly in GenerateFromTemplate.
This is a follow-up to 17be5b88af8e27a6e0c5887a2b20e67d55c9a914 . That commit didn't help with the problem of compile failures in files generated for BURS. The compile failures occur very seldomly on IA32 but regularly on PPC64.

An example failure looks like this:

compile:
    [mkdir] Created dir: /home/regression/jenkins/workspace/x86-sanity-tier2-main-repo/target/BaseBaseMarkCompact_x86_64-linux/classes
    [javac] Compiling 97 source files to /home/regression/jenkins/workspace/x86-sanity-tier2-main-repo/target/BaseBaseMarkCompact_x86_64-linux/classes
    [javac] /home/regression/jenkins/workspace/x86-sanity-tier2-main-repo/generated/main/java/org/jikesrvm/compilers/opt/lir2mir/ia32_32/BURS_STATE.java:16358: error: unclosed comment
    [javac]   /**
    [javac]   ^
    [javac] /home/regression/jenkins/workspace/x86-sanity-tier2-main-repo/generated/main/java/org/jikesrvm/compilers/opt/lir2mir/ia32_32/BURS_STATE.java:16360: error: reached end of file while parsing
    [javac]    *
    [javac]     ^
    [javac] /home/regression/jenkins/workspace/x86-sanity-tier2-main-repo/generated/main/java/org/jikesrvm/compilers/opt/lir2mir/ia32_32/BURS_STATE.java:51: error: BURS_STATE is not abstract and does not override abstract method code(AbstractBURS_TreeNode,int,int) in BURS_StateCoder
    [javac] public class BURS_STATE extends BURS_Helpers implements BURS_StateCoder {
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors