1) VM_TypeReference.resolve() now throws NoClassDefFoundError instead of the ClassNotFoundException it used to throw.<br> 2) Got rid of a number of try ... catch blocks that used to have to surround calls to VM_TypeReference.resolve(), and would throw an Internal Error. <br> 3) In a few places, we now explicitly catch NoClassDefFound errors, generally where we used to catch ClassNotFoundException. <br> 4) Made other changes I needed to make the code compile. 5) We now run the Eclipse regression tests.  Not perfectly, but we run them.