RVM-549 : Start work on proper initialization of java.lang.System
As mentioned in the last commit, the method initializeSystemclass() has to be called to properly initialize java.lang.System. This commit has a few changes to make progress on this.

The implementation currently uses the shared Jikes RVM implementation of java.lang.Class. To make further progress, Open JDK's implementation of java.lang.Class has to be used. This is evident in the failure that occurs with the current state of implementation during boot image writing:

RVMClass: (begin) instantiate java.lang.System$2
MethodReference.resolveInternal(): Unable to find a method named getConstantPool with descriptor ()Lsun/reflect/ConstantPool; in the class Ljava/lang/Class;, while writing the boot image
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at org.jikesrvm.classloader.MethodReference.resolveInternal(MethodReference.java:362)
	at org.jikesrvm.classloader.MethodReference.peekResolvedMethod(MethodReference.java:201)
	at org.jikesrvm.classloader.MemberReference.peekResolvedMember(MemberReference.java:263)
	at org.jikesrvm.classloader.MemberReference.needsDynamicLink(MemberReference.java:293)
	at org.jikesrvm.compilers.baseline.TemplateCompilerFramework.genCode(TemplateCompilerFramework.java:1456)
	at org.jikesrvm.compilers.baseline.BaselineCompiler.compile(BaselineCompiler.java:295)
	at org.jikesrvm.compilers.baseline.BaselineCompiledMethod.compile(BaselineCompiledMethod.java:103)
	at org.jikesrvm.compilers.baseline.BaselineCompiler.compile(BaselineCompiler.java:219)
	at org.jikesrvm.compilers.baseline.BaselineBootImageCompiler.compileMethod(BaselineBootImageCompiler.java:49)
	at org.jikesrvm.compilers.common.BootImageCompiler.compile(BootImageCompiler.java:81)
	at org.jikesrvm.compilers.common.BootImageCompiler.compile(BootImageCompiler.java:89)
	at org.jikesrvm.classloader.NormalMethod.genCode(NormalMethod.java:181)
	at org.jikesrvm.classloader.RVMMethod.compile(RVMMethod.java:646)
	at org.jikesrvm.classloader.RVMMethod.getCurrentEntryCodeArray(RVMMethod.java:624)
	at org.jikesrvm.classloader.RVMClass.instantiate(RVMClass.java:1603)
	at org.jikesrvm.tools.bootImageWriter.BootImageWorker.run(BootImageWorker.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Error: MethodReference.resolveInternal(): Unable to resolve a method during boot image writing
	at org.jikesrvm.classloader.MethodReference.resolveInternal(MethodReference.java:363)
	at org.jikesrvm.classloader.MethodReference.peekResolvedMethod(MethodReference.java:201)
	at org.jikesrvm.classloader.MemberReference.peekResolvedMember(MemberReference.java:263)
	at org.jikesrvm.classloader.MemberReference.needsDynamicLink(MemberReference.java:293)
	at org.jikesrvm.compilers.baseline.TemplateCompilerFramework.genCode(TemplateCompilerFramework.java:1456)
	at org.jikesrvm.compilers.baseline.BaselineCompiler.compile(BaselineCompiler.java:295)
	at org.jikesrvm.compilers.baseline.BaselineCompiledMethod.compile(BaselineCompiledMethod.java:103)
	at org.jikesrvm.compilers.baseline.BaselineCompiler.compile(BaselineCompiler.java:219)
	at org.jikesrvm.compilers.baseline.BaselineBootImageCompiler.compileMethod(BaselineBootImageCompiler.java:49)
	at org.jikesrvm.compilers.common.BootImageCompiler.compile(BootImageCompiler.java:81)
	at org.jikesrvm.compilers.common.BootImageCompiler.compile(BootImageCompiler.java:89)
	at org.jikesrvm.classloader.NormalMethod.genCode(NormalMethod.java:181)
	at org.jikesrvm.classloader.RVMMethod.compile(RVMMethod.java:646)
	at org.jikesrvm.classloader.RVMMethod.getCurrentEntryCodeArray(RVMMethod.java:624)
	at org.jikesrvm.classloader.RVMClass.instantiate(RVMClass.java:1603)
	at org.jikesrvm.tools.bootImageWriter.BootImageWorker.run(BootImageWorker.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Error:
BootImageWriter: Failure during instantiation of java.lang.System$2
	at org.jikesrvm.tools.bootImageWriter.BootImageWriterMessages.fail(BootImageWriterMessages.java:30)
	at org.jikesrvm.tools.bootImageWriter.BootImageWorker.run(BootImageWorker.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Killing VM due to failure in thread Thread[pool-1-thread-1,5,main]