This is a repeat of the checkin done at 2004/03/15 20:08:44, but lost due to a rollback of the CVS repository.
If the VM isn't fully booted, VM_MethodReference.resolveInternal() doesn't try
to throw a new NoSuchMethodError.