Try out workaround for build failures on the regression machines
The failures look like this:

    [mkdir] Created dir: /jenkins/workspace/x64-sanity-main-repo/target/BaseBaseGenRC_x86_64_m64-linux/bootimage-writer
    [javac] Compiling 23 source files to /jenkins/workspace/x64-sanity-main-repo/target/BaseBaseGenRC_x86_64_m64-linux/bootimage-writer
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /jenkins/workspace/x64-sanity-main-repo/tools/bootImageWriter/src/org/jikesrvm/tools/bootImageWriter/BootImageWriter.java:2683: error: cannot access JikesRVMSupport
    [javac]           Object vmcons = java.lang.reflect.JikesRVMSupport.createVMConstructor(constructor);
    [javac]                                            ^
    [javac]   bad class file: /jenkins/workspace/x64-sanity-main-repo/target/BaseBaseGenRC_x86_64_m64-linux/rvmrt.jar(java/lang/reflect/JikesRVMSupport.class)
    [javac]     unable to access file: corrupted zip file
    [javac]     Please remove or make sure it appears in the correct subdirectory of the classpath.
    [javac] 1 error
    [javac] 1 warning